{{- if .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doda-sms-app.fullname" . }}-app
  labels:
    {{- include "doda-sms-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "doda-sms-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  # Template for each pod
  template:
    metadata:
      labels:
        {{- include "doda-sms-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
      - name: {{ .Values.app.name }}
        # Docker image to use
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.app.service.targetPort }}
          protocol: TCP

        env:
        - name: MODEL_HOST
          value: "http://{{ include "doda-sms-app.fullname" . }}-model:{{ .Values.modelService.service.port }}"
        {{- if .Values.app.config.enabled }}
        - name: APP_CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: {{ include "doda-sms-app.fullname" . }}-config
              key: app-config
        {{- end }}
        {{- if .Values.app.secret.enabled }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "doda-sms-app.fullname" . }}-secret
              key: smtp-password
        {{- end }}
        # Liveness checks
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30 # Wait 30 seconds before first check
          periodSeconds: 10 # Check every 10 seconds after that
        # Readiness cheks
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10 # Wait 10 seconds before first check
          periodSeconds: 5 # Check every 5 seconds
        # CPU and memory limits (from values.yaml)
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
{{- end }}
