{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "doda-sms-app.fullname" . }}-grafana
  labels:
    {{- include "doda-sms-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  ports:
  - port: {{ .Values.monitoring.grafana.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "doda-sms-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
