{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "doda-sms-app.fullname" . }}-model
  labels:
    {{- include "doda-sms-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-service
spec:
  host: {{ include "doda-sms-app.fullname" . }}-model
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: {{ .Values.istio.stickySession.headerName | default "x-user-id" }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}
