{{- if and .Values.monitoring.enabled .Values.app.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "doda-sms-app.fullname" . }}-monitor
  labels:
    release: {{ .Values.app.prometheus.releaseLabel }}
    {{- include "doda-sms-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "doda-sms-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  endpoints:
    - port: http
      path: /sms/metrics
      interval: {{ .Values.app.prometheus.serviceMonitor.interval }}
{{- end }}
