{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
{{- $promName := printf "%s-prometheus" (include "doda-sms-app.fullname" .) -}}
{{- $saName := default $promName .Values.monitoring.prometheus.serviceAccount.name -}}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ $promName }}
  labels:
    release: {{ .Values.app.prometheus.releaseLabel }}
    {{- include "doda-sms-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitoring.prometheus.replicaCount }}
  serviceAccountName: {{ $saName }}
  retention: {{ .Values.monitoring.prometheus.retention }}
  scrapeInterval: {{ .Values.monitoring.prometheus.scrapeInterval }}
  evaluationInterval: {{ .Values.monitoring.prometheus.evaluationInterval }}
  serviceMonitorSelector:
    matchLabels:
      release: {{ .Values.app.prometheus.releaseLabel }}
  ruleSelector:
    matchLabels:
      release: {{ .Values.app.prometheus.releaseLabel }}
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name: {{ printf "%s-alertmanager" (include "doda-sms-app.fullname" .) }}
      port: web
  {{- with .Values.monitoring.prometheus.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.monitoring.prometheus.storage.enabled }}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.monitoring.prometheus.storage.size }}
  {{- end }}
{{- end }}
