{{- if .Values.app.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doda-sms-app.fullname" . }}-secret
  labels:
    {{- include "doda-sms-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Values must be base64 encoded
  # The value from values.yaml should be base64 encoded or use stringData instead
  smtp-password: {{ .Values.app.secret.smtpPassword | b64enc | quote }}
{{- end }}
