{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume      
metadata:
  name: model-service-pv      
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  {{- if eq .Values.persistence.storageType "hostPath" }}
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
    type: Directory
  {{- end }}
{{- end }}

---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-service-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}