{{- if .Values.istio.enabled }}
# routing rules for traffic entering through the Gateway, connecting gateway to backend service
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helm.fullname" . }}-vs
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.istio.gateway.name }}
  
  hosts:
  - "*" # accept all
  
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ include "helm.fullname" . }}-service
        port:
          number: {{ .Values.app.service.port }}
{{- end }}
