---
# Source: doda-sms-app/templates/ingress.yaml
# Allows external traffic to reach your app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # name
  name: sms-test-doda-sms-app-app
  labels:
    helm.sh/chart: doda-sms-app-1.0.0
    app.kubernetes.io/name: doda-sms-app
    app.kubernetes.io/instance: sms-test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  ingressClassName: nginx
  rules:
  - host: sms-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 8080
