---
- hosts: all
  become: true
  tasks:
    - name: Generate join command from controller
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl

    - name: Join the node to the cluster
      ansible.builtin.shell: "{{ join_command.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
